# Generated by Django 4.2.1 on 2024-02-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_medico', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Api', models.CharField(max_length=500)),
                ('ApiKeys', models.CharField(max_length=500)),
            ],
        ),
    ]
