# Generated by Django 4.2.1 on 2024-02-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section_medico', '0003_apikeys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
