# Generated by Django 4.2.1 on 2024-01-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_di_venere', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prenotazioni',
        ),
    ]
